export const SPREAD_FACTOR = 45;
export const SLIDE_MILLIS = 500;
export const SLIDE_DELAY_MILLIS = 1;
export const ON_MOVE_DELAY_MILLIS = 2;

export const mainCongratulations = [
  "Congratulations!",
  "Well done",
  "Nice one",
  "Very good",
  "Excellent",
  "Splendid",
  "Terrific",
  "Sterling work",
  "Astounding!",
  "Astonishing",
  "Impressive",
  "Goodness me",
  "Fabulous",
  "Awesome sauce",
  "Very nice indeed",
  "Well look at you!",
  "Ohh, get you!",
  "Proper good, that",
  "Flabbergasting"
];

export const zerothCompliments = [
  "You truly are the",
  "You're basically the",
  "You could almost be the",
  "You remind me of the",
  "You're absolutely the",
  "You're definitely the",
  "You really are the",
  "You're what they call the",
  "You're pretty much the",
  "Yes! You're now the",
  "Wow, that was the"
];

export const firstCompliments = [
  "bee's",
  "dog's",
  "giraffe's",
  "monkey's",
  "king's",
  "queen's",
  "rightful",
  "most awesome",
  "stupendous",
  "hobnob's",
  "people's",
  "pope's",
  "foremost",
  "fire's",
  "bicycle's",
  "tallest",
  "most humble",
  "reddest",
  "loudest",
  "strangest",
  "coldest",
  "tricycle's",
  "most fabulous",
  "jam",
  "jammy",
  "red",
  "green",
  "blue",
  "hot",
  "warm",
  "real",
  "proper",
  "most illustrious",
  "most beatific",
  "gentlest",
  "kindest",
  "weirdest",
  "definition of the"
];

export const secondCompliments = [
  "knees",
  "champion",
  "delight",
  "nose",
  "neck",
  "winner",
  "Freeceller",
  "chocolate",
  "flame",
  "basket",
  "tree",
  "face",
  "voice",
  "sort of awesome",
  "trusted advisor",
  "winter",
  "mountain",
  "third wheel",
  "sceptre",
  "kind of winner",
  "sort of person",
  "doughnut",
  "dodger",
  "best friend",
  "thing",
  "stuff",
  "hobnob",
  "biscuit",
  "Ferrari",
  "equivalent of a Good Thing™",
  "equal",
  "idea of splendid",
  "idea of a good time",
  "hair",
  "ear",
  "neck"
];

export const playAgainLabels = [
  "More, please",
  "More of this",
  "Again!",
  "Do it again",
  "Back to it",
  "Don't stop",
  "Get on with it",
  "Let's have another",
  "One for the road",
  "Just one more game",
  "And again",
  "Last one, honest",
  "Keep it going",
  "I can't stop",
  "I can't get enough",
  "I need more"
];