export const SPREAD_FACTOR = 45;

export const firstCompliments = [
  "bee's",
  "dog's",
  "giraffe's",
  "monkey's",
  "king's",
  "queen's",
  "rightful",
  "most awesome",
  "stupendous",
  "hobnob's",
  "people's",
  "pope's",
  "foremost",
  "fire's",
  "bicycle's",
  "tallest",
  "most humble",
  "reddest",
  "loudest",
  "strangest",
  "coldest",
  "tricycle's",
  "most fabulous",
  "jam",
  "jammy",
  "red",
  "green",
  "blue",
  "hot",
  "warm",
  "real",
  "proper",
  "most illustrious",
  "most beatific",
  "gentlest",
  "kindest",
  "weirdest",
  "definition of a"
];

export const secondCompliments = [
  "knees",
  "champion",
  "delight",
  "nose",
  "neck",
  "winner",
  "Freeceller",
  "chocolate",
  "flame",
  "basket",
  "tree",
  "face",
  "voice",
  "sort of awesome",
  "trusted advisor",
  "winter",
  "mountain",
  "third wheel",
  "sceptre",
  "kind of winner",
  "sort of person",
  "doughnut",
  "dodger",
  "best friend",
  "thing",
  "stuff",
  "hobnob",
  "biscuit",
  "Ferrari",
  "equivalent of a Good Thing™",
  "equal",
  "idea of splendid",
  "idea of a good time",
  "hair",
  "ear",
  "neck"
];